name: Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  coverage:
    uses: MoneyLion/actions/.github/workflows/run-coverage.yaml@main
    with:
      language: javascript
      test-command: CI=true npx react-scripts test --watchAll=false --coverage --coverageReporters=json-summary
    secrets: inherit
